### ISSUE TITLE
Addition of All Contributors Photos in Readme | Readme Updation

### ISSUE THREAD

**Issue by Shariq2003** [GlobeHoppin/GlobeHoppin#12]
We can add all the contributor's photos in Readme file as a token of appreciation for their work.

Please assign this to me.

![image](https://github.com/user-attachments/assets/24846984-f3d2-44a4-8d2b-2a5025d1ceb9)
Like this

**Comment by Mustafiz04** [comment]
Yeah we can do but keep picture size small so it won't take much space when contributor increase.

**Comment by Shariq2003** [comment]
> Yeah we can do but keep picture size small so it won't take much space when contributor increase. Add this section at last.

Sure sir, this is a demo please check, and also we can limit the number of contributors to show. eg., 10,100 etc.
![image](https://github.com/user-attachments/assets/6c3fb4f3-733e-4d4f-bb56-975ede67f869)

**Comment by Mustafiz04** [comment]
> Sure sir, this is a demo please check, and also we can limit the number of contributors to show. eg., 10,100 etc.

I see, yes limit it to 10, add `show more` button, when click redirect it to contributor page in our website.
can we also add link to their GitHub profile and so on ?

**Comment by Shariq2003** [comment]
> > Sure sir, this is a demo please check, and also we can limit the number of contributors to show. eg., 10,100 etc.
> 
> I see, yes limit it to 10, add `show more` button, when click redirect it to contributor page in our website. can we also add link to their GitHub profile and so on ?

Sure, I will do the same

**Comment by Shariq2003** [comment]
@Mustafiz04 do check the PR

**Comment by Mustafiz04** [comment]
I don't understand why are you creating new issue, you can easily do this issue only.

**Comment by Shariq2003** [comment]
> I don't understand why are you creating new issue, you can easily do this issue only.

sir I have raised a PR 4 hrs ago please check

**Comment by Shariq2003** [comment]
@Mustafiz04 sir sorry for this, i mistakenly raise this PR here, instead of raising in another repo, where the admin requested to create another one.
Actually I have splitted the windows side by side causing this issue.
Again sorry
