### ISSUE TITLE
Update text 

### ISSUE THREAD

**Issue by biswajit-sarkar-007** [GlobeHoppin/GlobeHoppin#129]
i want to update the text in bottom of the footer in this text  "© 2023 GlobeHoppin.All Rights Reserved." to new updated year 2024.

# Screenshot

![update-text-2024](https://github.com/user-attachments/assets/bfd7b302-34a6-4974-88b8-53ed3677dfbb)

**Comment by Mustafiz04** [comment]
Do this in your other PR only.
