### ISSUE TITLE
[Bug] Confirm Password Field Becomes Visible Automatically – Implement Toggle Visibility Feature

### ISSUE THREAD

**Issue by Dev-Rishav** [GlobeHoppin/GlobeHoppin#13]
**Description**

Currently, the confirm password field becomes visible automatically as soon as it's typed.
To improve the user experience, I propose adding an eye icon to toggle the visibility of the password in the input box.

If this issue aligns with the project's goals, please assign the relevant **GSSoC extended labels** for me to proceed. Thank You!

![Screenshot 2024-10-05 221940](https://github.com/user-attachments/assets/4a3cf60f-78c4-4360-9985-c0911c9cf1d4)

**Comment by Mustafiz04** [comment]
This is already covered in this issue #7
