### ISSUE TITLE
(Documentation) : Add code of conduct & Github Greetings Bot

### ISSUE THREAD

**Issue by KiranBaliga** [GlobeHoppin/GlobeHoppin#14]
Hey 🥳 Looks like an amazing project idea! I see this repo lacks a small enhancement Github Greetings bot that sends auto messages to greet new users when they raise a PR or an issue. Let me know if you would like this level1 set up! Please assign to me if interested! (GSSoC24-Ext Contribution), I will also add code of conduct as per the standard norms followed by GSSoC24.

**Comment by Mustafiz04** [comment]
Assigning it to you, but can you please elaborate little more what are you going to do.

**Comment by KiranBaliga** [comment]
@Mustafiz04 I will work on it and give an update/raise a PR.

**Comment by KiranBaliga** [comment]
@Mustafiz04 I have added two bots, one that will display a message when someone new raises a PR or an issue. Another, auto assigns the issue to those who create them. Unassign is still a manual process by the owner. Code of conduct has been added.

Please review and action accordingly.

Thank you!
