### ISSUE TITLE
[ FEATURE] Adding better Budge Calculator

### ISSUE THREAD

**Issue by IkkiOcean** [GlobeHoppin/GlobeHoppin#143]
## Current budget calculator lacks modern UI design and functionality to add multiple location or mentioning specific spendings.

<img width="875" alt="Screenshot 2024-10-24 at 3 29 06 AM" src="https://github.com/user-attachments/assets/efb23b30-aa7f-41a8-afff-1f406274e3d3">

## I suggest a new budget planner which will look like this:

<img width="722" alt="Screenshot 2024-10-24 at 3 31 20 AM" src="https://github.com/user-attachments/assets/a46b9137-4424-415d-827a-a6bb61207f59">

Note: this a demo, I will implement it according to the requirements and UI of GlobeHoppin

**Comment by Mustafiz04** [comment]
Sound interesting. Please upgrade this and make better UI.

**Comment by IkkiOcean** [comment]
@Mustafiz04 
<img width="1278" alt="Screenshot 2024-10-25 at 6 00 59 PM" src="https://github.com/user-attachments/assets/0fc068bd-92f8-4ae1-8fcb-c051d41b3df9">

hey I forked the repo to run it on my local. can you help me run it? its showing this error for contactPage. is there any other branch I should be working on?

**Comment by Mustafiz04** [comment]
Basically these are unused variable. You can remove those and run again.
