### ISSUE TITLE
Add Favicon.

### ISSUE THREAD

**Issue by ShivamTiwari0214** [GlobeHoppin/GlobeHoppin#17]
![image](https://github.com/user-attachments/assets/e805be5a-4259-4f3e-a5a6-9335046189ae)

I would like to request the addition of a favicon to enhance the branding of the GlobeHoppin website. A favicon will improve user recognition in browser tabs and contribute to a more professional appearance. Implementing this feature will help in establishing a distinct identity for our project.

@Mustafiz04 assign this issue to me.

**Comment by YasirKhan231** [comment]
Hey @GlobeHoppin assign this task to me

**Comment by Mustafiz04** [comment]
That is intensional. No changes are needed for now.
