### ISSUE TITLE
Login and Sign Up Links Show 404 Error Despite Route Configuration Updates

### ISSUE THREAD

**Issue by UsamaWalayat12** [GlobeHoppin/GlobeHoppin#2]
After updating the **NavLink** paths and configuring the routes correctly, the issue still persists, and the Login or Sign Up links continue to show a "Page Not Found" error. Further investigation is needed to identify any additional problems in the routing setup.
 
 
 

![Signup](https://github.com/user-attachments/assets/d043cc99-5b75-4ef0-8bcd-d588c024a896)

**Comment by Mustafiz04** [comment]
I am assigning it to you.
