### ISSUE TITLE
Update on website theme 

### ISSUE THREAD

**Issue by zakie2003** [GlobeHoppin/GlobeHoppin#28]
Hey there ,I m friend of Kartikey2011yadav a day prior you assigned him task of multiple generating multiple theme for your site. The thing is he got his account suspended from GitHub so he wont be able to login to his account. He is still working on your assigned task and he will be raising pr as soon as he gets his account back [Probably By coming Monday]

**Comment by aqueefcs** [comment]
@Mustafiz04 .

**Comment by Mustafiz04** [comment]
@zakie2003 Are you working on this or can I assign to someone else ?

**Comment by zakie2003** [comment]
Ok you may assign it to someone else because his account is still in suspended state
