### ISSUE TITLE
Addition of Architectural Flowchart For Better Understanding of the Process.

### ISSUE THREAD

**Issue by Shariq2003** [GlobeHoppin/GlobeHoppin#39]
![image](https://github.com/user-attachments/assets/c629f104-73aa-4edb-8ddc-56f518d62d0d)

These steps should also be represented in the form of Architecture or flowchart

**Comment by Mustafiz04** [comment]
This sounds very interesting.
Assigning it to you.
Based on work I will assign level on PR

**Comment by Shariq2003** [comment]
> This sounds very interesting. Assigning it to you. Based on work I will assign level on PR

Okay
