### ISSUE TITLE
add faq pop up model at resources at footer

### ISSUE THREAD

**Issue by ananyag309** [GlobeHoppin/GlobeHoppin#40]
Add an FAQ popup modal at the "Resources" section in the footer of website. The modal should provide frequently asked questions with clear answers to guide users through common queries. Ensure the design aligns with the professional and advanced look of the site.

**Comment by Mustafiz04** [comment]
Make sure it's not hardcoded. Data could be stored in a single file, then imported, looped through, and shown. Then we migrate it to the backend.
