### ISSUE TITLE
Github Workflow : Notify Contributors When Pull Requests Are Merged

### ISSUE THREAD

**Issue by samyak-aditya** [GlobeHoppin/GlobeHoppin#57]
Notify Contributors When Pull Requests Are Merged

### Issue Description
**Background:**
Currently, when a pull request (PR) is merged, contributors are not notified about the status of their contributions. It’s important to acknowledge their efforts and keep them informed to foster a positive and collaborative environment.

**Benefits:**
- Enhances contributor engagement.
- Acknowledges their work, which can encourage future contributions.
- Improves communication within the project.

Please assign me this issue with "level2"

**Comment by Mustafiz04** [comment]
This is not needed for now. Creating a new ticket and will tag you there.

Consider picking this https://github.com/GlobeHoppin/GlobeHoppin/issues/26.
