### ISSUE TITLE
Add Footer in the 'Contact us' Page

### ISSUE THREAD

**Issue by ishita-1305** [GlobeHoppin/GlobeHoppin#61]
Description:
There is no footer in the contact us page. Adding it will be better for user experience.
![Screenshot 2024-10-13 125623](https://github.com/user-attachments/assets/9aad5ad3-07cc-4d57-8a8f-fa9c1f6689c2)

**Comment by JacobGeoGeek** [comment]
can I work on this issue for the hacktoberfest 2024?

**Comment by Mustafiz04** [comment]
This is a line change just a footer component on this page.

Assigning to @ishita-1305

**Comment by Mustafiz04** [comment]
@JacobGeoGeek I am creating some new issues and will tag you there if you want to work.

**Comment by JacobGeoGeek** [comment]
@Mustafiz04, I would like to work on the #26 issue. However, is there any documentation on how to set up the development repo?
