### ISSUE TITLE
Low Visibility of Text in Footer Section

### ISSUE THREAD

**Issue by Priyanshu282003** [GlobeHoppin/GlobeHoppin#66]
Description: There is a visibility issue with the text under "Resources", "Follow Us", and "Legal" sections in the footer. The text appears too faint, making it difficult for users to read.

Steps to Reproduce:

Scroll down to the footer section of the website.
Observe the text under the "Resources", "Follow Us", and "Legal" headers.
Expected Behavior: The text should be clearly visible, with sufficient contrast against the background for easy readability.

Actual Behavior: The text appears too dark against the background, causing a readability issue.
Screenshots:
![image](https://github.com/user-attachments/assets/a6c65903-ef10-4cc4-b2f7-56c4238dbb0f)

**Comment by Mustafiz04** [comment]
This is fixed now by someone else.
