### ISSUE TITLE
Update Readme.md file 

### ISSUE THREAD

**Issue by Sadab-Hussain** [GlobeHoppin/GlobeHoppin#68]
Hii,
Please assign this issue to me. I would like to improve the README.md file by adding sections for 'About', 'Features', 'Screenshots', 'Technologies Used', 'How to Contribute', and other important information to make it more detailed and visually appealing.

ThankYou @GlobeHoppin

**Comment by Mustafiz04** [comment]
Thanks for this but we have enough information added.

Would you like to work on a coding task?
