### ISSUE TITLE
[BUG] No privacy-policy and terms page for the links in the footer

### ISSUE THREAD

**Issue by Vaishh18** [GlobeHoppin/GlobeHoppin#71]
There is no privacy-policy and terms page  for the links in the footer 

https://github.com/user-attachments/assets/ec8fdbc6-fe6d-4b60-8288-a13514ae5c91

I would like to work on this issue under gssoc-ext24 and hacktoberfest

**Comment by krishna7602** [comment]
i will like to contribute to fix this issue
