### ISSUE TITLE
Feature:Email verification

### ISSUE THREAD

**Issue by Hh440** [GlobeHoppin/GlobeHoppin#85]
### Description 
Implementing email verification will significantly enhance the website's security by ensuring that only authenticated users can gain access. This process will prevent anonymous individuals from entering the site, thereby safeguarding sensitive information and maintaining a trustworthy environment for all users.

**Comment by Mustafiz04** [comment]
Can we implement signup signin api and protected route in other task after this ???

**Comment by Hh440** [comment]
yes you can implement

**Comment by Mustafiz04** [comment]
> yes you can implement

I am asking you, do you wanna work and implement this ?

**Comment by Hh440** [comment]
so you want to implement signup and signin also

**Comment by Hh440** [comment]
i can do that if you want

**Comment by Mustafiz04** [comment]
> so you want to implement signup and signin also

Yes but not in this task. Sure, will assign you later.

**Comment by Hh440** [comment]
i want to ask some things

- you are not using any backend 
- to implement verification is better to use database such as postgress or any other

**Comment by Mustafiz04** [comment]
We are using backend.
https://github.com/GlobeHoppin/globe-hoppin-backend
